### ISSUE TITLE
error TS2589: Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by nerdlich-media** [NickSettler/event-system#1]
When i try to transpile your Event-System with tsc i get the following errors:

1. error TS2589: Type instantiation is excessively deep and possibly infinite.
export interface EventSystemSubscriber<E extends Record<string, (...args: Parameters<E[keyof E]>) => ReturnType<E[keyof E]>>, K extends keyof E> {
2. error TS2589: Type instantiation is excessively deep and possibly infinite.
export class EventSystem<E extends Record<string, (...args: Parameters<E[keyof E]>) => ReturnType<E[keyof E]>>>{
3. error TS2589: Type instantiation is excessively deep and possibly infinite.
public static create<E extends Record<string, (...args: Parameters<E[keyof E]>) => ReturnType<E[keyof E]>>>() {

How do i avoid these?

Edit: I use typescript Version 4.3.2

**Comment by NickSettler** [comment]
This projects uses typescript 4.7.4, which is defined in package.json. Obviously it is a bug in ts 4.3.2. You should try using typescript version from package.json while compiling the project

**Comment by nerdlich-media** [comment]
Thank you very much.
