### ISSUE TITLE
Use generic arguments

### ISSUE THREAD

**Issue by myalban** [NickSettler/event-system#2]
Hi,

Thanks, this class is unbelievable but do you think if there is  a way to use generic arguments also ?

I got this error 

`Type 'SysEvent' does not satisfy the constraint 'Record<string, (...args: [key: string] | [message: string, action: number]) => void>'.
  Property '[MYEVENT.KEY]' is incompatible with index signature.
    Type '(key: string) => void' is not assignable to type '(...args: [key: string] | [message: string, action: number]) => void'.
      Types of parameters 'key' and 'args' are incompatible.
        Type '[key: string] | [message: string, action: number]' is not assignable to type '[key: string]'.
          Type '[message: string, action: number]' is not assignable to type '[key: string]'.`

Exemple, an event wih only a key:string and another one with a message and action

`
/**
 * Event System Subscriber interface. The interface contains event from {@link EVENT_SYSTEM_EVENT_NAMES}
 * and the function that will be called when the event is triggered.
 *
 * @interface EventSystemSubscriber
 */
interface EventSystemSubscriber<
  E extends Record<
    string,
    (...args: Parameters<E[keyof E]>) => ReturnType<E[keyof E]>
  >,
  K extends keyof E
> {
  event: K;
  handler: (...args: Parameters<E[K]>) => void;
}

/**
 * Event System class. The class is used to manage events and trigger their handlers.
 */
class EventSystem<
  E extends Record<
    string,
    (...args: Parameters<E[keyof E]>) => ReturnType<E[keyof E]>
  >
> {
  /**
   * The Event System subscribers.
   * @type {EventSystemSubscriber<E, keyof E>[]}
   * @private
   */
  private subscribers: EventSystemSubscriber<E, keyof E>[] = [];

  /**
   * Subscribes handler to be called when the event is triggered.
   * @param {K extends keyof E & string} event The event name.
   * @param {(...args: Parameters<E[keyof E]>) => ReturnType<E[keyof E]>} handler The handler function.
   */
  public subscribe<K extends keyof E & string>(
    event: K,
    handler: (...args: Parameters<E[K]>) => ReturnType<E[K]>
  ) {
    this.subscribers.push({ event, handler });

  }

  /**
   * Unsubscribes the handler from the event.
   * @param {K extends keyof E & string} event The event name.
   * @param {(...args: Parameters<E[keyof E]>) => ReturnType<E[keyof E]>} handler The handler function.
   */
  public unsubscribe<K extends keyof E & string>(
    event: K,
    handler: (...args: Parameters<E[K]>) => ReturnType<E[K]>
  ) {
    this.subscribers = this.subscribers.filter(
      (subscriber) =>
        subscriber.event !== event || subscriber.handler !== handler
    );
  }

  /**
   * Triggers the event with the given arguments.
   * @param {K extends keyof E & string} event The event name.
   * @param {Parameters<EventSystemEvents[keyof E]>} args The arguments to pass to the handler.
   */
  public notify<K extends keyof E & string>(
    event: K,
    ...args: Parameters<E[K]>
  ) {
    this.subscribers.forEach((subscriber) => {
      if (subscriber.event === event)
        subscriber.handler.call(subscriber.handler, ...args);
    });

  }
}
enum MYEVENT {
    KEY = "KEY",
    BOOT = "BOOT"
    
  }
  
  type SysEvent = {
    [MYEVENT.KEY]: (key: string) => void;
    [MYEVENT.BOOT]: (message: string, action: number) => void;
  }

const eventSystem = new EventSystem<SysEvent>();
eventSystem.subscribe(MYEVENT.BOOT, (message, action) => {
  console.log(message, action)
  const onPress = (ev: KeyboardEvent) => {
    eventSystem.notify(MYEVENT.KEY, ev.key);
  };
  document.removeEventListener("keydown", onPress);
  document.addEventListener("keydown", onPress);

})

eventSystem.subscribe(MYEVENT.KEY, (key) => { console.log(key + " pressed") })
eventSystem.notify(MYEVENT.BOOT,"BOOT Complete",1)
`

[Link to TS file is here ](https://www.typescriptlang.org/play?ssl=104&ssc=51&pln=1&pc=1#code/FAegVGwARlCiA3ApgOwC5QMoE8DOakBbLAVwCNcBjAJwEsylqpb1GAzAQ0qQDooAVABZJmrap25RKAe3QcWuKEmToobatOIBvAAIAbFgGt4ANTgA5fgH1MATUz84AWStwzlq+YCCTuJgC+0LAcKAAmUGjCaiQolGi0shGCHBgA7rR6elAMUhyZSOGpwihJIsqoGLSKaHQA5rWMBTxBQVA6LATiXCKIFTj4RJjkVHQM1EEgwB3s3fAqaP0EhEMUNPSMADzQ8EoAHgRhigBKSDLUoVtQV1D4dCi1ADTbVwAUPO8c1LW4AFxQAAqfDiEJCdXAbOAAbUMSGw0jY8AAugA+ACUUAAvMioCc0CRqCh+NgAA5ICHQ2HwpHI7bIp5XADSewOoUUMLhCLgwGxWm25XQfwZAG5tskwnpGH83h8vr8AUCQWDyQyUeisVAENJaKERYFgKAIK1eqpFkQpHoOLhcHwhCJKBarcxFCRcAUItIoIQQhwGkp5ooQuEarR6oxSrQmGLQhLqNaJsB7ZbFMaFnglpcdkh9qhWTjTtJzhmrrcWI9nlBpTxPt8-oDqMDQYxwVD2VS4KrMdjcfjCSSyS3KZyUbTuVBeVdwJBrrBbXMKlg02bcMM1mM49O2mg+2OU6blivRps4A8oK3OcjIYjAhudMS6AgUkhnmBJlc77QHwQbgf1rG-rvF33VZD2oCETzPeAL0RTEoEvEV9QnQ0NxWEZ1kUKMY3dbI7TyCVCmKUo-XnKoIjqBpqCaZ82mJBUxyZLMWTZQcdgAMhuYN7n8IjVFnfkMBQBtmhvGj620StqzlOsGyVAcOWpNUu1BHsiVJckIPbZEuIwsNZ20pg2BiOIEhQISrhfbZiXIAxKG-YD1g2ejs0OU9mLgKA2JLe5kRecs+MFelrj0qV3irWVawVRtY2VDt1W7AkVP7SEVRpK50XHa5IiqHhlzstceEs3BBBeLRuLQE89KgfxUXg7Y9UQqczKgABVFActQhhqiiCr1E0Qi+NMmBqNorRHMYly5LcjyONqLi+IEKI5oEkEBtgW9hvEsL5VEyLmwpCaYsUvF4r7NTXJRLTA0w3TLrDAzYniWQVtfKBLLIayoBiNrVzJUacyYib3PYu5am83z5n88sgorEKJPC7aZKSg68yO3tVKhZLtjS8tMutL6QMUDEkiyvHf2tNgMk6HzrmuF4SbGBTy2punGB4OaAEIMUJuaAB9uds9qWYqjnCb08tqtqhCoEnKj+DIps+vmKB0kiQjag-VAoGrEgQXQddGrW0S6OZP7xrbQHPJm0r5rKRWlt4KiDeBMcpMVJsIXmPcU1wPa23OzXZWt-3am1ipqg9GjHTQD1IhEPSnosqzaBslBpHiNhsAc43nPU83ptB6m-KgBkAquGHNpdnbopSqAsepnHsp-PK2ALOAuCK2nG8YBSx0Z5gEQ73KWbmzmufmVFe+LTvqB4OPKFwgeBenvSTzL75xepqr4KuQJAlQbWoCcWw3Asfge+phk4FsGCACIL9sa+S6gAAhAB5F-T8J6-X-f6+JaubYtykgXLgFMMF0pXEhIfY+lgeB30RFKdkfwLbd01NqEU1NIFH3cPwHg39+DwIrCCK0PokBIOmieLgD0UB-BQNremnYNRah1BLBMsh8ClT3DBFASBUhznQHuDY-QUzeXFnxPcDdB4vCgdg3Bb9+AnheEQ3AJCKFGVkN3dKMhWrSAlDwPQ0haiKKQMQhoqiqHjyuFo9hsh-gUUdITF4yhBSwjINIT4oQUwaLBn0QCPAU5p2wFIrBJ9YGXxPMoHg7J16VXQVAUI0hKAh3QDwCihBpDIBTAAGSqAcRgLxr7sniakFAD8oA2LsbgaJ8TEk6zQFWUIHj5jZIGNw6g+TCnSGKaU8pxjKnwSqvqMRvjmZBOgTgu+CiokMJKlYnRvB9GGPZFAAA1FAa+L0KkFGvuiAZQyBiED8anWg6dRkyLwQ8L+cioAAGFNDEglAQB+ABGceQA)

best regards

**Comment by designbyadrian** [comment]
@myalban How did you solve this?
